# Generated by Django 2.0.4 on 2018-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180525_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='D:\\PyCharm\\project_django\\static\\media\\product_images'),
        ),
    ]
